//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole_MVC_Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechSpecsFan
    {
        public int ProductID { get; set; }
        public Nullable<int> AirFlowCFM { get; set; }
        public Nullable<int> PowerWattsMax { get; set; }
        public Nullable<int> PowerWattsMin { get; set; }
        public Nullable<int> OperatingVoltageMax { get; set; }
        public Nullable<int> OperatingVoltageMin { get; set; }
        public Nullable<int> FanSpeedMax { get; set; }
        public Nullable<int> FanSpeedMin { get; set; }
        public Nullable<int> NumbSpeed { get; set; }
        public Nullable<int> MaxSound { get; set; }
        public Nullable<int> SweepDiameter { get; set; }
        public Nullable<int> FanWeight { get; set; }
        public string MountingLocation { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
