//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole_MVC_Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechSpecsToaster
    {
        public int ProductID { get; set; }
        public Nullable<int> NumOfPrograms { get; set; }
        public Nullable<int> PowerWattsMax { get; set; }
        public Nullable<int> PowerWattsMin { get; set; }
        public Nullable<int> OperatingVoltageMax { get; set; }
        public Nullable<int> OperatingVoltageMin { get; set; }
        public Nullable<int> HeatMax { get; set; }
        public Nullable<int> HeatMin { get; set; }
        public Nullable<int> OutputPerHour { get; set; }
        public Nullable<int> SlotWidth { get; set; }
        public Nullable<int> ToasterHeight { get; set; }
        public Nullable<int> ToasterWeight { get; set; }
        public string Slot { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
